// src/components/RevisionCard.tsx
import React, { useState, useEffect } from 'react';
import type { Question } from '../core/quiz';
import { generateOptions, checkAnswer } from '../core/quiz';
import type { PokemonType } from '../core/typeChart';
import { getTypeStyle } from '../data/typeMetadata';
import { TypeButton } from './TypeButton';
import { SquareButton } from './SquareButton';

interface RevisionCardProps {
  question: Question;
  onAnswerSubmit: (isCorrect: boolean) => void;
}

export const RevisionCard: React.FC<RevisionCardProps> = ({
  question,
  onAnswerSubmit,
}) => {
  const [options, setOptions] = useState<PokemonType[]>([]);
  const [selectedTypes, setSelectedTypes] = useState<PokemonType[]>([]);
  const [isAnswered, setIsAnswered] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);

  useEffect(() => {
    // Generate options when question changes
    const generatedOptions = generateOptions(question.correctAnswers, 8);
    setOptions(generatedOptions);
    setSelectedTypes([]);
    setIsAnswered(false);
  }, [question]);

  const handleSkip = () => {
    setIsAnswered(true);
    onAnswerSubmit(false);
  };

  const handleTypeSelect = (type: PokemonType) => {
    if (isAnswered) return;

    setSelectedTypes((prev) =>
      prev.includes(type)
        ? prev.filter((t) => t !== type)
        : [...prev, type]
    );
  };

  const handleSubmit = () => {
    const correct = checkAnswer(question, selectedTypes);
    setIsCorrect(correct);
    setIsAnswered(true);
    onAnswerSubmit(correct);
  };

  const getCategoryText = (): string => {
    switch (question.category) {
      case 'weaknesses':
        return 'Select types that are **super effective** against:';
      case 'resistances':
        return 'Select types that are **not very effective** against:';
      case 'immunities':
        return 'Select types that deal **0 damage** to:';
      default:
        return 'Select the correct types:';
    }
  };

  const defendingTypeDisplay =
    question.defendingTypes.length === 1
      ? question.defendingTypes[0]
      : `${question.defendingTypes[0]}/${question.defendingTypes[1]}`;

  const defendingStyle = getTypeStyle(question.defendingTypes[0]);

  return (
    <div className="w-full max-w-2xl mx-auto p-6 bg-white rounded-xl shadow-lg">
      {/* Question Header */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4">
          {getCategoryText().replace(/\*\*/g, '')}
        </h2>

        {/* Defending Type Display */}
        <div
          className="inline-flex items-center gap-4 px-6 py-4 rounded-lg mb-4"
          style={{ backgroundColor: defendingStyle.bgColor }}
        >
          <img
            src={`/types/${question.defendingTypes[0].toLowerCase()}.svg`}
            alt={question.defendingTypes[0]}
            className="w-16 h-16 object-contain"
          />
          <div>
            <div
              className="text-2xl font-bold"
              style={{ color: defendingStyle.textColor }}
            >
              {defendingTypeDisplay}
            </div>
            <div className="text-sm text-gray-600">
              Type{question.defendingTypes.length > 1 ? 's' : ''}
            </div>
          </div>
        </div>
      </div>

      {/* Options Grid */}
      <div className="mb-8">
        <p className="text-sm font-semibold text-gray-600 mb-4">
          {selectedTypes.length > 0
            ? `Selected: ${selectedTypes.length} / ${question.correctAnswers.length}`
            : `Select ${question.correctAnswers.length} type${question.correctAnswers.length !== 1 ? 's' : ''}`}
        </p>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-6">
          {options.map((type) => (
            <TypeButton
              key={type}
              type={type}
              isSelected={selectedTypes.includes(type)}
              onClick={() => handleTypeSelect(type)}
              disabled={isAnswered}
            />
          ))}
        </div>
      </div>

      {/* Feedback */}
      {isAnswered && (
        <div
          className={`p-4 rounded-lg mb-6 ${
            isCorrect
              ? 'bg-green-100 text-green-800'
              : 'bg-red-100 text-red-800'
          }`}
        >
          <p className="font-semibold mb-2">
            {isCorrect ? '✓ Correct!' : '✗ Incorrect'}
          </p>
          <p className="text-sm">
            {isCorrect
              ? `Great job! You correctly identified all the ${question.category} against ${defendingTypeDisplay}.`
              : `The correct answer is: ${question.correctAnswers.join(', ')}`}
          </p>
        </div>
      )}

      {/* Buttons Section */}
      {!isAnswered && (
        <div className="flex gap-4 mt-8 pt-6 border-t border-gray-200 justify-center">
          <SquareButton
            onClick={handleSubmit}
            disabled={selectedTypes.length !== question.correctAnswers.length}
            className={`${
              selectedTypes.length === question.correctAnswers.length
                ? 'bg-green-500 hover:bg-green-600 text-white cursor-pointer'
                : 'bg-gray-300 text-gray-400 cursor-not-allowed opacity-60'
            }
          `}
            title="Submit answer"
          >
            <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-6 h-6">
              <path d="M20 6L9 17L4 12" stroke="#22c55e" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            <span className="text-sm font-bold whitespace-nowrap">Submit</span>
          </SquareButton>
          <SquareButton
            onClick={handleSkip}
            className="bg-gray-400 hover:bg-gray-500 text-white"
            title="Skip question"
          >
            <svg viewBox="0 0 24 24" fill="white" xmlns="http://www.w3.org/2000/svg" className="w-6 h-6">
              <path d="M5 4v16M19 12l-8-6v12l8-6Z"/>
            </svg>
            <span className="text-sm font-bold whitespace-nowrap">Skip</span>
          </SquareButton>
        </div>
      )}
    </div>
  );
};

// src/lib/components/RevisionCard.svelte
<script lang="ts">
  import type { Question, PokemonType } from '$lib/core/types';
  import { generateOptions, checkAnswer, getTypeStyle } from '$lib/core/types';
  import TypeButton from './TypeButton.svelte';

  export let question: Question;
  export let onAnswerSubmit: (isCorrect: boolean) => void = () => {};

  let options: PokemonType[] = [];
  let selectedTypes: PokemonType[] = [];
  let isAnswered = false;
  let isCorrect = false;

  $: {
    options = generateOptions(question.correctAnswers, 8);
    selectedTypes = [];
    isAnswered = false;
    isCorrect = false;
  }

  const handleTypeSelect = (type: PokemonType) => {
    if (isAnswered) return;
    selectedTypes = selectedTypes.includes(type)
      ? selectedTypes.filter(t => t !== type)
      : [...selectedTypes, type];
  };

  const handleSubmit = () => {
    isCorrect = checkAnswer(question, selectedTypes);
    isAnswered = true;
    onAnswerSubmit(isCorrect);
  };

  const handleSkip = () => {
    isAnswered = true;
    onAnswerSubmit(false);
  };

  const getCategoryText = (): string => {
    switch (question.category) {
      case 'weaknesses': return 'Select types that are super effective against:';
      case 'resistances': return 'Select types that are not very effective against:';
      case 'immunities': return 'Select types that deal 0 damage to:';
    }
  };

  $: defendingTypeDisplay = question.defendingTypes.length === 1
    ? question.defendingTypes[0]
    : `${question.defendingTypes[0]}/${question.defendingTypes[1]}`;
    
  $: defendingStyle = getTypeStyle(question.defendingTypes[0]);
</script>

<div class="revision-card animate-scale-in">
  <div class="question-header">
    <h2 class="question-prompt">{getCategoryText()}</h2>
    
    <div class="defending-type" style="--def-bg: {defendingStyle.bgColor}">
      <img 
        src="/types/{question.defendingTypes[0].toLowerCase()}.svg" 
        alt={question.defendingTypes[0]}
        class="defending-icon"
      />
      <div class="defending-info">
        <span class="defending-name" style="color: {defendingStyle.textColor}">{defendingTypeDisplay}</span>
        <span class="defending-label">Type{question.defendingTypes.length > 1 ? 's' : ''}</span>
      </div>
    </div>
  </div>

  <div class="options-section">
    <p class="selection-hint">
      {#if selectedTypes.length > 0}
        Selected: {selectedTypes.length} / {question.correctAnswers.length}
      {:else}
        Select {question.correctAnswers.length} type{question.correctAnswers.length !== 1 ? 's' : ''}
      {/if}
    </p>
    
    <div class="options-grid">
      {#each options as type (type)}
        <TypeButton 
          {type}
          isSelected={selectedTypes.includes(type)}
          onClick={() => handleTypeSelect(type)}
        />
      {/each}
    </div>
  </div>

  {#if isAnswered}
    <div class="feedback" class:correct={isCorrect} class:incorrect={!isCorrect}>
      <p class="feedback-title">{isCorrect ? '✓ Correct!' : '✗ Incorrect'}</p>
      <p class="feedback-text">
        {isCorrect 
          ? `Great job! You correctly identified all the ${question.category} against ${defendingTypeDisplay}.`
          : `The correct answer is: ${question.correctAnswers.join(', ')}`}
      </p>
    </div>
  {:else}
    <div class="actions">
      <button 
        class="action-btn submit"
        class:enabled={selectedTypes.length === question.correctAnswers.length}
        disabled={selectedTypes.length !== question.correctAnswers.length}
        on:click={handleSubmit}
      >
        <svg viewBox="0 0 24 24" fill="none" class="btn-icon">
          <path d="M20 6L9 17L4 12" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        Submit
      </button>
      <button class="action-btn skip" on:click={handleSkip}>
        <svg viewBox="0 0 24 24" fill="currentColor" class="btn-icon">
          <path d="M5 4v16M19 12l-8-6v12l8-6Z"/>
        </svg>
        Skip
      </button>
    </div>
  {/if}
</div>

<style>
  .revision-card {
    width: 100%;
    max-width: 42rem;
    margin: 0 auto;
    padding: 2rem;
    background: var(--card-bg);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-lg);
    border: 1px solid var(--border);
  }

  .question-header {
    margin-bottom: 2rem;
    text-align: center;
  }

  .question-prompt {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 1.5rem;
    color: var(--text-h);
  }

  .defending-type {
    display: inline-flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem 1.5rem;
    background: var(--def-bg);
    border-radius: var(--radius-lg);
  }

  .defending-icon {
    width: 4rem;
    height: 4rem;
    object-fit: contain;
  }

  .defending-info {
    display: flex;
    flex-direction: column;
    gap: 0;
  }

  .defending-name {
    font-size: 1.75rem;
    font-weight: 700;
  }

  .defending-label {
    font-size: 0.8rem;
    color: var(--text);
    opacity: 0.7;
  }

  .options-section {
    margin-bottom: 1.5rem;
  }

  .selection-hint {
    text-align: center;
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--text);
    margin-bottom: 1rem;
    opacity: 0.8;
  }

  .options-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 0.75rem;
    justify-items: center;
  }

  @media (max-width: 480px) {
    .options-grid {
      grid-template-columns: repeat(3, 1fr);
    }
  }

  .feedback {
    padding: 1rem;
    border-radius: var(--radius);
    text-align: center;
    animation: fadeIn 0.3s var(--ease-out);
  }

  .feedback.correct {
    background: rgba(16, 185, 129, 0.15);
    border: 1px solid var(--success);
  }

  .feedback.incorrect {
    background: rgba(239, 68, 68, 0.15);
    border: 1px solid var(--danger);
  }

  .feedback-title {
    font-weight: 700;
    font-size: 1.1rem;
    margin-bottom: 0.25rem;
  }

  .feedback.correct .feedback-title {
    color: var(--success);
  }

  .feedback.incorrect .feedback-title {
    color: var(--danger);
  }

  .feedback-text {
    font-size: 0.9rem;
    color: var(--text);
  }

  .actions {
    display: flex;
    justify-content: center;
    gap: 1rem;
    padding-top: 1.5rem;
    border-top: 1px solid var(--border);
  }

  .action-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: var(--radius);
    font-size: 0.9rem;
    font-weight: 600;
    transition: all 0.2s var(--ease-out);
  }

  .action-btn.submit {
    background: linear-gradient(135deg, #10b981, #059669);
    color: white;
  }

  .action-btn.submit.enabled {
    box-shadow: var(--shadow);
  }

  .action-btn.submit:disabled {
    background: #d1d5db;
    color: #9ca3af;
    cursor: not-allowed;
  }

  .action-btn.skip {
    background: #6b7280;
    color: white;
  }

  .action-btn.skip:hover {
    background: #4b5563;
  }

  .btn-icon {
    width: 1.25rem;
    height: 1.25rem;
  }
</style>
