// src/components/ScoreDisplay.tsx
import React from 'react';

interface ScoreDisplayProps {
  correct: number;
  total: number;
  streak?: number;
}

export const ScoreDisplay: React.FC<ScoreDisplayProps> = ({
  correct,
  total,
  streak = 0,
}) => {
  const percentage = total > 0 ? Math.round((correct / total) * 100) : 0;

  return (
    <div className="flex items-center justify-between gap-4 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl shadow-lg border border-blue-100">
      {/* Score */}
      <div className="flex flex-col gap-1">
        <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide">Progress</div>
        <div className="flex items-baseline gap-1">
          <span className="text-3xl font-bold text-blue-600">{correct}</span>
          <span className="text-gray-400 text-lg">/</span>
          <span className="text-2xl font-semibold text-gray-700">{total}</span>
        </div>
      </div>

      {/* Percentage */}
      <div className="flex flex-col items-center gap-2">
        <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide">Accuracy</div>
        <div
          className={`text-3xl font-bold rounded-xl w-20 h-20 flex items-center justify-center transition-all ${
            percentage >= 75
              ? 'bg-gradient-to-br from-green-400 to-green-600 text-white shadow-lg'
              : percentage >= 50
                ? 'bg-gradient-to-br from-yellow-400 to-yellow-600 text-white shadow-lg'
                : 'bg-gradient-to-br from-red-400 to-red-600 text-white shadow-lg'
          }`}
        >
          {percentage}%
        </div>
      </div>

      {/* Streak */}
      {streak > 0 && (
        <div className="flex flex-col items-center gap-2">
          <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide">Streak</div>
          <div className="flex items-center gap-1 bg-gradient-to-r from-orange-400 to-pink-500 text-white px-4 py-2 rounded-xl font-bold shadow-lg">
            <span className="text-xl">🔥</span>
            <span className="text-2xl">{streak}</span>
          </div>
        </div>
      )}
    </div>
  );
};

// src/lib/components/ScoreDisplay.svelte
<script lang="ts">
  export let correctVal: number = 0;
  export let totalVal: number = 0;
  export let streak: number = 0;

  $: percentage = totalVal > 0 ? Math.round((correctVal / totalVal) * 100) : 0;
  
  $: accuracyColor = percentage >= 75 ? 'var(--success)' : percentage >= 50 ? 'var(--warning)' : 'var(--danger)';
</script>

<div class="score-display">
  <div class="score-section">
    <span class="label">Progress</span>
    <div class="score-value">
      <span class="correct">{correctVal}</span>
      <span class="sep">/</span>
      <span class="total">{totalVal}</span>
    </div>
  </div>

  <div class="score-section center">
    <span class="label">Accuracy</span>
    <div class="accuracy-circle" style="background: {accuracyColor}">
      {percentage}%
    </div>
  </div>

  {#if streak > 0}
    <div class="score-section">
      <span class="label">Streak</span>
      <div class="streak-badge">
        <span class="fire">🔥</span>
        <span class="streak-num">{streak}</span>
      </div>
    </div>
  {/if}
</div>

<style>
  .score-display {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 1.5rem;
    padding: 1.25rem 1.5rem;
    background: var(--card-bg);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow);
    border: 1px solid var(--border);
  }

  .score-section {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.25rem;
  }

  .score-section.center {
    align-items: center;
  }

  .label {
    font-size: 0.7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text);
    opacity: 0.7;
  }

  .score-value {
    display: flex;
    align-items: baseline;
    gap: 0.25rem;
  }

  .correct {
    font-size: 2rem;
    font-weight: 700;
    color: var(--accent);
  }

  .sep {
    font-size: 1.25rem;
    opacity: 0.4;
  }

  .total {
    font-size: 1.25rem;
    font-weight: 500;
    color: var(--text-h);
  }

  .accuracy-circle {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 4rem;
    height: 4rem;
    border-radius: var(--radius);
    font-size: 1.1rem;
    font-weight: 700;
    color: white;
    box-shadow: var(--shadow);
  }

  .streak-badge {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.5rem 1rem;
    background: linear-gradient(135deg, #f59e0b, #ef4444);
    border-radius: var(--radius);
    color: white;
  }

  .streak-num {
    font-size: 1.5rem;
    font-weight: 700;
  }
</style>
